# Generated by Django 4.2.7 on 2025-11-23 02:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_kind', models.CharField(default='ciudadano', help_text='Tipo de reportante: ciudadano, operador, sistema', max_length=20)),
                ('reporter_id', models.UUIDField(blank=True, help_text='ID del usuario que reportó', null=True)),
                ('type', models.CharField(choices=[('punto_acopio', 'Punto de Acopio'), ('zona_critica', 'Zona Crítica'), ('animal_muerto', 'Animal Fallecido'), ('zona_reciclaje', 'Zona de Reciclaje')], help_text='Tipo de incidente reportado', max_length=30)),
                ('title', models.CharField(help_text='Título descriptivo del incidente', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del incidente', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Ubicación geográfica del incidente (lat, lon)', srid=4326)),
                ('address', models.CharField(blank=True, help_text='Dirección aproximada', max_length=255, null=True)),
                ('status', models.CharField(choices=[('incidente_no_validado', 'No Validado'), ('incidente_pendiente', 'Pendiente Validación'), ('incidente_valido', 'Válido'), ('incidente_rechazado', 'Rechazado'), ('convertido_en_tarea', 'Convertido en Tarea'), ('cerrado', 'Cerrado')], default='incidente_no_validado', help_text='Estado actual del incidente', max_length=30)),
                ('incident_day', models.DateField(default=django.utils.timezone.now, help_text='Día en que ocurrió el incidente (UTC)')),
                ('photos_count', models.IntegerField(default=0, help_text='Número de fotos/evidencias adjuntas')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Clave para prevenir duplicados desde app móvil', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(help_text='Tipo de agregado: incident, task, etc.', max_length=50)),
                ('aggregate_id', models.UUIDField(help_text='ID del agregado relacionado')),
                ('event_type', models.CharField(help_text='Tipo de evento a publicar', max_length=50)),
                ('payload', models.JSONField(help_text='Payload completo del evento')),
                ('routing_key', models.CharField(help_text='Routing key para RabbitMQ', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Número de intentos de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento Outbox',
                'verbose_name_plural': 'Eventos Outbox',
                'db_table': 'outbox_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_even_status_8ec420_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_even_aggrega_d56a15_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Tipo de evento: incidente_creado, estado_actualizado, etc.', max_length=50)),
                ('payload', models.JSONField(blank=True, help_text='Datos adicionales del evento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Evento de Incidente',
                'verbose_name_plural': 'Eventos de Incidentes',
                'db_table': 'incident_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(help_text='URL del archivo en storage (S3, Cloudinary, etc.)', max_length=500)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo MIME del archivo', max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Adjunto de Incidente',
                'verbose_name_plural': 'Adjuntos de Incidentes',
                'db_table': 'incident_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-created_at'], name='incidents_status_0ce7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['type', '-created_at'], name='incidents_type_b7ff70_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reporter_id'], name='incidents_reporte_aca25f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_day'], name='incidents_inciden_01baf6_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['incident', '-created_at'], name='incident_ev_inciden_13ae0b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['event_type'], name='incident_ev_event_t_313d41_idx'),
        ),
    ]
